/*
 * Project 'WS-Aggregation':
 * http://www.infosys.tuwien.ac.at/prototype/WS-Aggregation/
 *
 * Copyright 2010-2012 Vienna University of Technology
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 4.1d1 */
package at.ac.tuwien.infosys.aggr.waql;

public interface ParserTreeConstants
{
  public int JJTPARSE = 0;
  public int JJTPDATADEPENDENCY = 1;
  public int JJTPPATHEXPRCDATA = 2;
  public int JJTPDATADEPENDENCYCDATA = 3;
  public int JJTPTEMPLATELIST = 4;
  public int JJTPESCAPEDOLLAR = 5;
  public int JJTPWAQLEXTENSION = 6;
  public int JJTPMODULE = 7;
  public int JJTPVERSIONDECL = 8;
  public int JJTPMAINMODULE = 9;
  public int JJTPLIBRARYMODULE = 10;
  public int JJTPMODULEDECL = 11;
  public int JJTPPROLOG = 12;
  public int JJTPSEPARATOR = 13;
  public int JJTPSETTER = 14;
  public int JJTPBOUNDARYSPACEDECL = 15;
  public int JJTPDEFAULTCOLLATIONDECL = 16;
  public int JJTPBASEURIDECL = 17;
  public int JJTPCONSTRUCTIONDECL = 18;
  public int JJTPORDERINGMODEDECL = 19;
  public int JJTPEMPTYORDERDECL = 20;
  public int JJTPCOPYNAMESPACESDECL = 21;
  public int JJTPPRESERVEMODE = 22;
  public int JJTPINHERITMODE = 23;
  public int JJTPDECIMALFORMATDECL = 24;
  public int JJTPDFPROPERTYNAME = 25;
  public int JJTPIMPORT = 26;
  public int JJTPSCHEMAIMPORT = 27;
  public int JJTPSCHEMAPREFIX = 28;
  public int JJTPMODULEIMPORT = 29;
  public int JJTPNAMESPACEDECL = 30;
  public int JJTPDEFAULTNAMESPACEDECL = 31;
  public int JJTPANNOTATEDDECL = 32;
  public int JJTPANNOTATION = 33;
  public int JJTPVARDECL = 34;
  public int JJTPVARVALUE = 35;
  public int JJTPVARDEFAULTVALUE = 36;
  public int JJTPCONTEXTITEMDECL = 37;
  public int JJTPFUNCTIONDECL = 38;
  public int JJTPPARAMLIST = 39;
  public int JJTPPARAM = 40;
  public int JJTPFUNCTIONBODY = 41;
  public int JJTPENCLOSEDEXPR = 42;
  public int JJTPOPTIONDECL = 43;
  public int JJTPQUERYBODY = 44;
  public int JJTPEXPR = 45;
  public int JJTPEXPRSINGLE = 46;
  public int JJTPFLWOREXPR = 47;
  public int JJTPINITIALCLAUSE = 48;
  public int JJTPINTERMEDIATECLAUSE = 49;
  public int JJTPFORCLAUSE = 50;
  public int JJTPFORBINDING = 51;
  public int JJTPALLOWINGEMPTY = 52;
  public int JJTPPOSITIONALVAR = 53;
  public int JJTPLETCLAUSE = 54;
  public int JJTPLETBINDING = 55;
  public int JJTPWINDOWCLAUSE = 56;
  public int JJTPTUMBLINGWINDOWCLAUSE = 57;
  public int JJTPSLIDINGWINDOWCLAUSE = 58;
  public int JJTPWINDOWSTARTCONDITION = 59;
  public int JJTPWINDOWENDCONDITION = 60;
  public int JJTPWINDOWVARS = 61;
  public int JJTPCURRENTITEM = 62;
  public int JJTPPREVIOUSITEM = 63;
  public int JJTPNEXTITEM = 64;
  public int JJTPCOUNTCLAUSE = 65;
  public int JJTPWHERECLAUSE = 66;
  public int JJTPGROUPBYCLAUSE = 67;
  public int JJTPGROUPINGSPECLIST = 68;
  public int JJTPGROUPINGSPEC = 69;
  public int JJTPORDERBYCLAUSE = 70;
  public int JJTPORDERSPECLIST = 71;
  public int JJTPORDERSPEC = 72;
  public int JJTPORDERMODIFIER = 73;
  public int JJTPRETURNCLAUSE = 74;
  public int JJTPQUANTIFIEDEXPR = 75;
  public int JJTPSWITCHEXPR = 76;
  public int JJTPSWITCHCASECLAUSE = 77;
  public int JJTPSWITCHCASEOPERAND = 78;
  public int JJTPTYPESWITCHEXPR = 79;
  public int JJTPCASECLAUSE = 80;
  public int JJTPSEQUENCETYPEUNION = 81;
  public int JJTPIFEXPR = 82;
  public int JJTPTRYCATCHEXPR = 83;
  public int JJTPTRYCLAUSE = 84;
  public int JJTPTRYTARGETEXPR = 85;
  public int JJTPCATCHCLAUSE = 86;
  public int JJTPCATCHERRORLIST = 87;
  public int JJTPCATCHVARS = 88;
  public int JJTPCATCHERRORCODE = 89;
  public int JJTPCATCHERRORDESC = 90;
  public int JJTPCATCHERRORVAL = 91;
  public int JJTPOREXPR = 92;
  public int JJTPANDEXPR = 93;
  public int JJTPCOMPARISONEXPR = 94;
  public int JJTPRANGEEXPR = 95;
  public int JJTPADDITIVEEXPR = 96;
  public int JJTPMULTIPLICATIVEEXPR = 97;
  public int JJTPUNIONEXPR = 98;
  public int JJTPINTERSECTEXCEPTEXPR = 99;
  public int JJTPINSTANCEOFEXPR = 100;
  public int JJTPTREATEXPR = 101;
  public int JJTPCASTABLEEXPR = 102;
  public int JJTPCASTEXPR = 103;
  public int JJTPUNARYEXPR = 104;
  public int JJTPVALUEEXPR = 105;
  public int JJTPGENERALCOMP = 106;
  public int JJTPVALUECOMP = 107;
  public int JJTPNODECOMP = 108;
  public int JJTPVALIDATEEXPR = 109;
  public int JJTPVALIDATIONMODE = 110;
  public int JJTPEXTENSIONEXPR = 111;
  public int JJTPPRAGMA = 112;
  public int JJTPPATHEXPR = 113;
  public int JJTPRELATIVEPATHEXPR = 114;
  public int JJTPSTEPEXPR = 115;
  public int JJTPAXISSTEP = 116;
  public int JJTPFORWARDSTEP = 117;
  public int JJTPFORWARDAXIS = 118;
  public int JJTPABBREVFORWARDSTEP = 119;
  public int JJTPREVERSESTEP = 120;
  public int JJTPREVERSEAXIS = 121;
  public int JJTPABBREVREVERSESTEP = 122;
  public int JJTPNODETEST = 123;
  public int JJTPNAMETEST = 124;
  public int JJTPWILDCARD = 125;
  public int JJTPPOSTFIXEXPR = 126;
  public int JJTPARGUMENTLIST = 127;
  public int JJTPPREDICATELIST = 128;
  public int JJTPPREDICATE = 129;
  public int JJTPLITERAL = 130;
  public int JJTPNUMERICLITERAL = 131;
  public int JJTPVARREF = 132;
  public int JJTPVARNAME = 133;
  public int JJTPPARENTHESIZEDEXPR = 134;
  public int JJTPCONTEXTITEMEXPR = 135;
  public int JJTPORDEREDEXPR = 136;
  public int JJTPUNORDEREDEXPR = 137;
  public int JJTPFUNCTIONCALL = 138;
  public int JJTPARGUMENT = 139;
  public int JJTPARGUMENTPLACEHOLDER = 140;
  public int JJTPCONSTRUCTOR = 141;
  public int JJTPDIRECTCONSTRUCTOR = 142;
  public int JJTPDIRELEMCONSTRUCTOR = 143;
  public int JJTPDIRATTRIBUTELIST = 144;
  public int JJTPDIRATTRIBUTEVALUE = 145;
  public int JJTPQUOTATTRVALUECONTENT = 146;
  public int JJTPAPOSATTRVALUECONTENT = 147;
  public int JJTPDIRELEMCONTENT = 148;
  public int JJTPDIRCOMMENTCONSTRUCTOR = 149;
  public int JJTPDIRPICONSTRUCTOR = 150;
  public int JJTPCDATASECTION = 151;
  public int JJTPCOMPUTEDCONSTRUCTOR = 152;
  public int JJTPCOMPDOCCONSTRUCTOR = 153;
  public int JJTPCOMPELEMCONSTRUCTOR = 154;
  public int JJTPCONTENTEXPR = 155;
  public int JJTPCOMPATTRCONSTRUCTOR = 156;
  public int JJTPCOMPNAMESPACECONSTRUCTOR = 157;
  public int JJTPPREFIX = 158;
  public int JJTPPREFIXEXPR = 159;
  public int JJTPURIEXPR = 160;
  public int JJTPCOMPTEXTCONSTRUCTOR = 161;
  public int JJTPCOMPCOMMENTCONSTRUCTOR = 162;
  public int JJTPCOMPPICONSTRUCTOR = 163;
  public int JJTPFUNCTIONITEMEXPR = 164;
  public int JJTPLITERALFUNCTIONITEM = 165;
  public int JJTPINLINEFUNCTION = 166;
  public int JJTPSINGLETYPE = 167;
  public int JJTPTYPEDECLARATION = 168;
  public int JJTPSEQUENCETYPE = 169;
  public int JJTPOCCURRENCEINDICATOR = 170;
  public int JJTPITEMTYPE = 171;
  public int JJTPATOMICORUNIONTYPE = 172;
  public int JJTPKINDTEST = 173;
  public int JJTPANYKINDTEST = 174;
  public int JJTPDOCUMENTTEST = 175;
  public int JJTPTEXTTEST = 176;
  public int JJTPCOMMENTTEST = 177;
  public int JJTPNAMESPACENODETEST = 178;
  public int JJTPPITEST = 179;
  public int JJTPATTRIBUTETEST = 180;
  public int JJTPATTRIBNAMEORWILDCARD = 181;
  public int JJTPSCHEMAATTRIBUTETEST = 182;
  public int JJTPATTRIBUTEDECLARATION = 183;
  public int JJTPELEMENTTEST = 184;
  public int JJTPELEMENTNAMEORWILDCARD = 185;
  public int JJTPSCHEMAELEMENTTEST = 186;
  public int JJTPELEMENTDECLARATION = 187;
  public int JJTPATTRIBUTENAME = 188;
  public int JJTPELEMENTNAME = 189;
  public int JJTPTYPENAME = 190;
  public int JJTPFUNCTIONTEST = 191;
  public int JJTPANYFUNCTIONTEST = 192;
  public int JJTPTYPEDFUNCTIONTEST = 193;
  public int JJTPPARENTHESIZEDITEMTYPE = 194;
  public int JJTPURILITERAL = 195;
  public int JJTPEQNAME = 196;
  public int JJTPINTEGERLITERAL = 197;
  public int JJTPPRIMARYEXPR = 198;
  public int JJTPCOMMONCONTENT = 199;
  public int JJTPNONRESERVEDKEYWORDS = 200;
  public int JJTPQNAME = 201;
  public int JJTPNCNAME = 202;


  public String[] jjtNodeName = {
    "parse",
    "pDataDependency",
    "pPathExprCdata",
    "pDataDependencyCdata",
    "pTemplateList",
    "pEscapeDollar",
    "pWAQLExtension",
    "pModule",
    "pVersionDecl",
    "pMainModule",
    "pLibraryModule",
    "pModuleDecl",
    "pProlog",
    "pSeparator",
    "pSetter",
    "pBoundarySpaceDecl",
    "pDefaultCollationDecl",
    "pBaseURIDecl",
    "pConstructionDecl",
    "pOrderingModeDecl",
    "pEmptyOrderDecl",
    "pCopyNamespacesDecl",
    "pPreserveMode",
    "pInheritMode",
    "pDecimalFormatDecl",
    "pDFPropertyName",
    "pImport",
    "pSchemaImport",
    "pSchemaPrefix",
    "pModuleImport",
    "pNamespaceDecl",
    "pDefaultNamespaceDecl",
    "pAnnotatedDecl",
    "pAnnotation",
    "pVarDecl",
    "pVarValue",
    "pVarDefaultValue",
    "pContextItemDecl",
    "pFunctionDecl",
    "pParamList",
    "pParam",
    "pFunctionBody",
    "pEnclosedExpr",
    "pOptionDecl",
    "pQueryBody",
    "pExpr",
    "pExprSingle",
    "pFLWORExpr",
    "pInitialClause",
    "pIntermediateClause",
    "pForClause",
    "pForBinding",
    "pAllowingEmpty",
    "pPositionalVar",
    "pLetClause",
    "pLetBinding",
    "pWindowClause",
    "pTumblingWindowClause",
    "pSlidingWindowClause",
    "pWindowStartCondition",
    "pWindowEndCondition",
    "pWindowVars",
    "pCurrentItem",
    "pPreviousItem",
    "pNextItem",
    "pCountClause",
    "pWhereClause",
    "pGroupByClause",
    "pGroupingSpecList",
    "pGroupingSpec",
    "pOrderByClause",
    "pOrderSpecList",
    "pOrderSpec",
    "pOrderModifier",
    "pReturnClause",
    "pQuantifiedExpr",
    "pSwitchExpr",
    "pSwitchCaseClause",
    "pSwitchCaseOperand",
    "pTypeswitchExpr",
    "pCaseClause",
    "pSequenceTypeUnion",
    "pIfExpr",
    "pTryCatchExpr",
    "pTryClause",
    "pTryTargetExpr",
    "pCatchClause",
    "pCatchErrorList",
    "pCatchVars",
    "pCatchErrorCode",
    "pCatchErrorDesc",
    "pCatchErrorVal",
    "pOrExpr",
    "pAndExpr",
    "pComparisonExpr",
    "pRangeExpr",
    "pAdditiveExpr",
    "pMultiplicativeExpr",
    "pUnionExpr",
    "pIntersectExceptExpr",
    "pInstanceofExpr",
    "pTreatExpr",
    "pCastableExpr",
    "pCastExpr",
    "pUnaryExpr",
    "pValueExpr",
    "pGeneralComp",
    "pValueComp",
    "pNodeComp",
    "pValidateExpr",
    "pValidationMode",
    "pExtensionExpr",
    "pPragma",
    "pPathExpr",
    "pRelativePathExpr",
    "pStepExpr",
    "pAxisStep",
    "pForwardStep",
    "pForwardAxis",
    "pAbbrevForwardStep",
    "pReverseStep",
    "pReverseAxis",
    "pAbbrevReverseStep",
    "pNodeTest",
    "pNameTest",
    "pWildcard",
    "pPostfixExpr",
    "pArgumentList",
    "pPredicateList",
    "pPredicate",
    "pLiteral",
    "pNumericLiteral",
    "pVarRef",
    "pVarName",
    "pParenthesizedExpr",
    "pContextItemExpr",
    "pOrderedExpr",
    "pUnorderedExpr",
    "pFunctionCall",
    "pArgument",
    "pArgumentPlaceholder",
    "pConstructor",
    "pDirectConstructor",
    "pDirElemConstructor",
    "pDirAttributeList",
    "pDirAttributeValue",
    "pQuotAttrValueContent",
    "pAposAttrValueContent",
    "pDirElemContent",
    "pDirCommentConstructor",
    "pDirPIConstructor",
    "pCDataSection",
    "pComputedConstructor",
    "pCompDocConstructor",
    "pCompElemConstructor",
    "pContentExpr",
    "pCompAttrConstructor",
    "pCompNamespaceConstructor",
    "pPrefix",
    "pPrefixExpr",
    "pURIExpr",
    "pCompTextConstructor",
    "pCompCommentConstructor",
    "pCompPIConstructor",
    "pFunctionItemExpr",
    "pLiteralFunctionItem",
    "pInlineFunction",
    "pSingleType",
    "pTypeDeclaration",
    "pSequenceType",
    "pOccurrenceIndicator",
    "pItemType",
    "pAtomicOrUnionType",
    "pKindTest",
    "pAnyKindTest",
    "pDocumentTest",
    "pTextTest",
    "pCommentTest",
    "pNamespaceNodeTest",
    "pPITest",
    "pAttributeTest",
    "pAttribNameOrWildcard",
    "pSchemaAttributeTest",
    "pAttributeDeclaration",
    "pElementTest",
    "pElementNameOrWildcard",
    "pSchemaElementTest",
    "pElementDeclaration",
    "pAttributeName",
    "pElementName",
    "pTypeName",
    "pFunctionTest",
    "pAnyFunctionTest",
    "pTypedFunctionTest",
    "pParenthesizedItemType",
    "pURILiteral",
    "pEQName",
    "pIntegerLiteral",
    "pPrimaryExpr",
    "pCommonContent",
    "pNonReservedKeywords",
    "pQName",
    "pNCName",
  };
}
/* JavaCC - OriginalChecksum=f202f1d74385fc331bbbc6c79f4ddaea (do not edit this line) */
